In [1]:
import numpy as np
import pandas as pd
from itertools import combinations

The problem is to match the user's free-form input against a pre-determined list of banks. For example, user input 'bawag bank' should be matched to 'BAWAG Group AG'.

In [2]:
# List of banks to compare
banks =   ['Sberbank Europe AG',
          'BAWAG Group AG',
          'Raiffeisenbankengruppe OÖ Verbund eGen',
          'Raiffeisen Bank International AG',
          'Volksbanken Verbund',
          'Erste Group Bank AG',
          'KBC Groep',
          'Investeringsmaatschappij Argenta',
          'Belfius Bank',
          'AXA Bank Belgium',
          'The Bank of New York Mellon SA/NV',
          'First Investment Bank AD',
          'RCB Bank Ltd',
          'Bank of Cyprus Holdings Public Limited Company',
          'Hellenic Bank Public Company Limited',
          'DekaBank Deutsche Girozentrale',
          'Erwerbsgesellschaft der S-Finanzgruppe mbH & Co. KG',
          'UBS Europe SE',
          'DEUTSCHE APOTHEKER- UND ÄRZTEBANK EG',
          'Volkswagen Bank Gesellschaft mit beschränkter Haftung',
          'Münchener Hypothekenbank eG',
          'DZ BANK AG Deutsche Zentral-Genossenschaftsbank, Frankfurt am Main',
          'HASPA Finanzholding',
          'State Street Europe Holdings Germany S.a.r.l. & Co. KG',
          'J.P. Morgan AG',
          'DEUTSCHE BANK AKTIENGESELLSCHAFT',
          'COMMERZBANK Aktiengesellschaft',
          'Landesbank Baden-Württemberg',
          'Landesbank Hessen-Thüringen Girozentrale',
          'Norddeutsche Landesbank - Girozentrale -',
          'Deutsche Pfandbriefbank AG',
          'Aareal Bank AG',
          'Hamburg Commercial Bank AG',
          'Bayerische Landesbank',
          'Jyske Bank A/S',
          'Sydbank A/S',
          'Nykredit Realkredit A/S',
          'Danske Bank A/S',
          'Luminor Holding AS',
          'Abanca Corporacion Bancaria S.A.',
          'Banco Santander S.A.',
          'Ibercaja Banco S.A.',
          'Kutxabank S.A',
          'Unicaja Banco S.A.',
          'CaixaBank S.A.',
          'Banco de Crédito Social Cooperativo',
          'Banco Bilbao Vizcaya Argentaria S.A.',
          'Banco de Sabadell S.A.',
          'Bankinter S.A.',
          'Kuntarahoitus Oyj',
          'Nordea Bank Abp',
          'OP Osuuskunta',
          'SFIL',
          'RCI Banque',
          'Confédération Nationale du Crédit Mutuel',
          'La Banque Postale',
          'Bpifrance',
          "C.R.H. - Caisse de refinancement de l'habitat",
          'HSBC Continental Europe',
          'Groupe BPCE',
          'Groupe Crédit Agricole',
          'Société générale',
          'BNP Paribas',
          'ALPHA SERVICES AND HOLDINGS S.A.',
          'National Bank of Greece S.A.',
          'Eurobank Ergasias Services and Holdings S.A.',
          'Piraeus Financial Holdings',
          'OTP-csoport',
          'Magyar Bankholding',
          'Barclays Bank Ireland plc',
          'Citibank Holdings Ireland Limited',
          'AIB Group plc',
          'Bank of Ireland Group plc',
          'Ulster Bank Ireland Designated Activity Company',
          'Bank of America Europe Designated Activity Company',
          'Íslandsbanki hf.',
          'Landsbankinn hf.',
          'Arion banki hf',
          'Intesa Sanpaolo S.p.A.',
          'Gruppo Bancario Finecobank  ',
          'UniCredit S.p.A.',
          'Gruppo Bancario Mediolanum  ',
          'Credito Emiliano Holding S.p.A.',
          'Banco BPM SpA',
          'Banca Popolare di Sondrio, Società Cooperativa per Azioni',
          'Banca Monte dei Paschi di Siena S.p.A.',
          'CASSA CENTRALE BANCA',
          'ICCREA BANCA S.P.A.',
          'Mediobanca - Banca di Credito Finanziario S.p.A.',
          'Akcine bendrove Šiauliu bankas',
          'Precision Capital S.A.',
          'RBC Investor Services Bank S.A.',
          'J.P. Morgan Bank Luxembourg S.A.',
          'Banque Internationale à Luxembourg',
          'Banque et Caisse d´Epargne de l´Etat, Luxembourg',
          'Akciju sabiedriba "Citadele banka"',
          'MDB Group Limited',
          'Bank of Valletta Plc',
          'HSBC Bank Malta p.l.c.',
          'BNG Bank N.V.',
          'ING Groep N.V.',
          'LP Group B.V.',
          'de Volksbank N.V.',
          'ABN AMRO Bank N.V.',
          'Coöperatieve Rabobank U.A.',
          'Nederlandse Waterschapsbank N.V.',
          'Bank Polska Kasa Opieki S.A.',
          'Powszechna Kasa Oszczednosci Bank Polski S.A.',
          'LSF Nani Investments S.à r.l.',
          'Banco Comercial Português SA',
          'Caixa Geral de Depósitos SA',
          'Banca Transilvania',
          'Länförsäkringar Bank AB (publ)',
          'Kommuninvest - group',
          'Skandinaviska Enskilda Banken - group',
          'SBAB Bank AB - group',
          'Swedbank - group',
          'Svenska Handelsbanken - group',
          'Biser Topco S.à r.l.',
          'Nova Ljubljanska Banka d.d. Ljubljana']

In [3]:
# Examples of search strings
s1 = 'Bawag bank' # other options: 'Bawag bank', 'Erste', 'Raiffaisen bank'

In [4]:
preprocessed_banks = [bank.lower() for bank in banks]
preprocessed_s1 = s1.lower()

In [5]:
from difflib import SequenceMatcher
res = []
i = 0
for token in preprocessed_banks:
  res.append([s1, banks[i], SequenceMatcher(None, preprocessed_s1, token).ratio()])
  i = i + 1

df2 = pd.DataFrame(res, columns=['Bank 1', 'Bank 2', 'Score'])
# The outcome is not great, for this search query 'BAWAG Group AG' should have highest similarity
df2.sort_values(by=['Score'], ascending=[False]).head()

        Bank 1          Bank 2     Score
99  Bawag bank   BNG Bank N.V.  0.608696
31  Bawag bank  Aareal Bank AG  0.583333
1   Bawag bank  BAWAG Group AG  0.583333
8   Bawag bank    Belfius Bank  0.545455
12  Bawag bank    RCB Bank Ltd  0.545455

In [6]:
 #The desired combination has a low score
idx = df2['Bank 2'].isin(['BAWAG Group AG'])

df2[idx].sort_values(by=['Score'], ascending=[False]).head()

       Bank 1          Bank 2     Score
1  Bawag bank  BAWAG Group AG  0.583333

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

#vectorize the texts
tf_idf_matrix = tfidf_vectorizer.fit_transform(preprocessed_banks + [preprocessed_s1])

In [8]:
tfidf_vectorizer.vocabulary_

{'sberbank': 219,
 'europe': 98,
 'ag': 7,
 'bawag': 39,
 'group': 113,
 'raiffeisenbankengruppe': 207,
 'oö': 189,
 'verbund': 245,
 'egen': 88,
 'raiffeisen': 206,
 'bank': 30,
 'international': 132,
 'volksbanken': 248,
 'erste': 93,
 'kbc': 142,
 'groep': 112,
 'investeringsmaatschappij': 135,
 'argenta': 19,
 'belfius': 41,
 'axa': 23,
 'belgium': 42,
 'the': 235,
 'of': 182,
 'new': 176,
 'york': 252,
 'mellon': 166,
 'sa': 213,
 'nv': 180,
 'first': 104,
 'investment': 136,
 'ad': 6,
 'rcb': 209,
 'ltd': 155,
 'cyprus': 75,
 'holdings': 126,
 'public': 204,
 'limited': 150,
 'company': 64,
 'hellenic': 122,
 'dekabank': 79,
 'deutsche': 83,
 'girozentrale': 110,
 'erwerbsgesellschaft': 94,
 'der': 81,
 'finanzgruppe': 100,
 'mbh': 162,
 'co': 60,
 'kg': 143,
 'ubs': 239,
 'se': 220,
 'apotheker': 18,
 'und': 241,
 'ärztebank': 254,
 'eg': 87,
 'volkswagen': 249,
 'gesellschaft': 109,
 'mit': 167,
 'beschränkter': 44,
 'haftung': 118,
 'münchener': 171,
 'hypothekenbank': 128,
 'dz': 86,
 'zentral': 253,
 'genossenschaftsbank': 106,
 'frankfurt': 105,
 'am': 14,
 'main': 160,
 'haspa': 121,
 'finanzholding': 101,
 'state': 230,
 'street': 231,
 'germany': 108,
 'morgan': 169,
 'aktiengesellschaft': 12,
 'commerzbank': 63,
 'landesbank': 148,
 'baden': 25,
 'württemberg': 251,
 'hessen': 123,
 'thüringen': 236,
 'norddeutsche': 177,
 'pfandbriefbank': 193,
 'aareal': 0,
 'hamburg': 119,
 'commercial': 62,
 'bayerische': 40,
 'jyske': 140,
 'sydbank': 234,
 'nykredit': 181,
 'realkredit': 211,
 'danske': 76,
 'luminor': 156,
 'holding': 125,
 'as': 22,
 'abanca': 2,
 'corporacion': 69,
 'bancaria': 27,
 'banco': 29,
 'santander': 217,
 'ibercaja': 129,
 'kutxabank': 146,
 'unicaja': 242,
 'caixabank': 54,
 'de': 77,
 'crédito': 73,
 'social': 225,
 'cooperativo': 68,
 'bilbao': 45,
 'vizcaya': 246,
 'argentaria': 20,
 'sabadell': 214,
 'bankinter': 36,
 'kuntarahoitus': 145,
 'oyj': 188,
 'nordea': 178,
 'abp': 4,
 'op': 183,
 'osuuskunta': 185,
 'sfil': 222,
 'rci': 210,
 'banque': 37,
 'confédération': 65,
 'nationale': 174,
 'du': 85,
 'crédit': 72,
 'mutuel': 170,
 'la': 147,
 'postale': 200,
 'bpifrance': 50,
 'caisse': 52,
 'refinancement': 212,
 'habitat': 117,
 'hsbc': 127,
 'continental': 66,
 'groupe': 114,
 'bpce': 49,
 'agricole': 8,
 'société': 227,
 'générale': 116,
 'bnp': 48,
 'paribas': 190,
 'alpha': 13,
 'services': 221,
 'and': 17,
 'national': 173,
 'greece': 111,
 'eurobank': 97,
 'ergasias': 92,
 'piraeus': 194,
 'financial': 99,
 'otp': 187,
 'csoport': 74,
 'magyar': 159,
 'bankholding': 34,
 'barclays': 38,
 'ireland': 139,
 'plc': 195,
 'citibank': 59,
 'aib': 9,
 'ulster': 240,
 'designated': 82,
 'activity': 5,
 'america': 15,
 'íslandsbanki': 255,
 'hf': 124,
 'landsbankinn': 149,
 'arion': 21,
 'banki': 35,
 'intesa': 134,
 'sanpaolo': 216,
 'gruppo': 115,
 'bancario': 28,
 'finecobank': 103,
 'unicredit': 243,
 'mediolanum': 165,
 'credito': 71,
 'emiliano': 89,
 'bpm': 51,
 'spa': 229,
 'banca': 26,
 'popolare': 198,
 'di': 84,
 'sondrio': 228,
 'società': 226,
 'cooperativa': 67,
 'per': 192,
 'azioni': 24,
 'monte': 168,
 'dei': 78,
 'paschi': 191,
 'siena': 223,
 'cassa': 56,
 'centrale': 57,
 'iccrea': 130,
 'mediobanca': 164,
 'finanziario': 102,
 'akcine': 11,
 'bendrove': 43,
 'šiauliu': 256,
 'bankas': 32,
 'precision': 202,
 'capital': 55,
 'rbc': 208,
 'investor': 138,
 'luxembourg': 157,
 'internationale': 133,
 'et': 95,
 'epargne': 91,
 'etat': 96,
 'akciju': 10,
 'sabiedriba': 215,
 'citadele': 58,
 'banka': 31,
 'mdb': 163,
 'valletta': 244,
 'malta': 161,
 'bng': 47,
 'ing': 131,
 'lp': 153,
 'volksbank': 247,
 'abn': 3,
 'amro': 16,
 'coöperatieve': 70,
 'rabobank': 205,
 'nederlandse': 175,
 'waterschapsbank': 250,
 'polska': 196,
 'kasa': 141,
 'opieki': 184,
 'powszechna': 201,
 'oszczednosci': 186,
 'polski': 197,
 'lsf': 154,
 'nani': 172,
 'investments': 137,
 'comercial': 61,
 'português': 199,
 'caixa': 53,
 'geral': 107,
 'depósitos': 80,
 'transilvania': 238,
 'länförsäkringar': 158,
 'ab': 1,
 'publ': 203,
 'kommuninvest': 144,
 'skandinaviska': 224,
 'enskilda': 90,
 'banken': 33,
 'sbab': 218,
 'swedbank': 233,
 'svenska': 232,
 'handelsbanken': 120,
 'biser': 46,
 'topco': 237,
 'nova': 179,
 'ljubljanska': 152,
 'ljubljana': 151}

In [9]:
print(tf_idf_matrix)

  (0, 7)	0.4743843076158768
  (0, 98)	0.5435923877243564
  (0, 219)	0.6924354444249211
  (1, 113)	0.4925052544362116
  (1, 39)	0.6982099020634888
  (1, 7)	0.519558954319157
  (2, 88)	0.509804379152687
  (2, 245)	0.4693596541994533
  (2, 189)	0.509804379152687
  (2, 207)	0.509804379152687
  (3, 132)	0.6122240470731595
  (3, 30)	0.2728375965722248
  (3, 206)	0.6122240470731595
  (3, 7)	0.4194318517559382
  (4, 248)	0.735686760579589
  (4, 245)	0.6773219251640318
  (5, 93)	0.6917626985813834
  (5, 30)	0.30828399012021673
  (5, 113)	0.4492459786265988
  (5, 7)	0.47392341256239906
  (6, 112)	0.6773219251640318
  (6, 142)	0.735686760579589
  (7, 19)	0.7071067811865475
  (7, 135)	0.7071067811865475
  (8, 41)	0.9134024367698166
  :	:
  (112, 158)	0.5729525398568226
  (112, 30)	0.25533625258892684
  (113, 144)	0.838665013851093
  (113, 113)	0.544647587474824
  (114, 33)	0.5405998515782182
  (114, 90)	0.5405998515782182
  (114, 224)	0.5405998515782182
  (114, 113)	0.351077486348563
  (115, 218)	0.636545215842489
  (115, 1)	0.5860456571336463
  (115, 30)	0.2836763234477445
  (115, 113)	0.41338652549158195
  (116, 233)	0.838665013851093
  (116, 113)	0.544647587474824
  (117, 120)	0.6425921719825712
  (117, 232)	0.6425921719825712
  (117, 113)	0.4173135523960888
  (118, 237)	0.7071067811865475
  (118, 46)	0.7071067811865475
  (119, 151)	0.509804379152687
  (119, 152)	0.509804379152687
  (119, 179)	0.509804379152687
  (119, 31)	0.4693596541994533
  (120, 30)	0.43569264681934533
  (120, 39)	0.9000955046591185

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(tf_idf_matrix[-1], tf_idf_matrix[:-1])

In [11]:
res = pd.DataFrame({
    'Bank 1': [s1] * len(banks),
    'Bank 2': banks,
    'Score': cos_sim.flatten()
})

In [12]:
df2 = pd.DataFrame(res, columns=['Bank 1', 'Bank 2', 'Score'])
# The outcome is great, for this search query 'BAWAG Group AG' have the highest similarity
df2.sort_values(by=['Score'], ascending=[False]).head()

        Bank 1           Bank 2     Score
1   Bawag bank   BAWAG Group AG  0.628456
34  Bawag bank   Jyske Bank A/S  0.177352
8   Bawag bank     Belfius Bank  0.177352
99  Bawag bank    BNG Bank N.V.  0.177352
37  Bawag bank  Danske Bank A/S  0.177352